name: 360videos to onedrive

on:
  push:
    branches:
      - main
  schedule:
    #       分 时 日 月 周
    - cron: 3,30 15 * * *
  watch:
    types: started

jobs:
  run-it:
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    
    name: 360videos
    
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Install paddleocr
        run: |
          python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
          pip install "paddleocr==2.6.1.0"
        
      - name: Unzip config
        run: |
          mkdir -p ~/.config/rclone/
          unzip -P ${{ secrets.PASSWD }} rclone.zip -d ~/.config/rclone
      
      - name: Change localtime
        run: |
          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      
      - name: Download videos
        run: |
          sudo cp -p ./chromedriver /usr/local/bin
          sudo chmod 777 /usr/local/bin/chromedriver
          python ./360videoDownload.py
        env:
          PHONE: ${{ secrets.PHONE }}
          PW: ${{ secrets.PW }}
          SCKEY: ${{ secrets.SCKEY }}
          DD_URL: ${{ secrets.DD_URL }}

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash


      - name: Sync rclone
        run: |
          ls -a
          # 列出文件(此处不展示)
          # rclone mkdir onedrive:/360videos
          rclone copy ./ onedrive:/360videos
